# Path to your oh-my-zsh installation.
ZSH="$HOME/.oh-my-zsh"

PATH=$(~/scripts/path_helper -p --config)
export PATH

envFile=~/.env

if test -f "$envFile"; then
  source ~/.env
fi

eval $(load-env.sh)

# GVM
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

#Theme
ZSH_THEME=""

#Plugins
plugins=(
  git
  colorize
  command-not-found
  cp
  mosh
  fasd
  docker
  golang
  httpie
  kubectl
  gcloud
  terraform
  tmux
  z
)

#nnn

n() {
   declare -x +g NNN_TMPFILE=$(mktemp)
   trap "rm -f $NNN_TMPFILE" EXIT
   =nnn -Ade $@
   [ -s $NNN_TMPFILE ] && source $NNN_TMPFILE
 }

eval "$(starship init zsh)"

source $ZSH/oh-my-zsh.sh
